apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostel-app
  labels:
    app: hostel-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hostel-app
  template:
    metadata:
      labels:
        app: hostel-app
    spec:
      containers:
      - name: hostel-app
        image: hostelregistry2024.azurecr.io/hostel-app:latest
        ports:
        - containerPort: 3001
        env:
        - name: DB_SERVER
          valueFrom:
            configMapKeyRef:
              name: hostel-config
              key: DB_SERVER
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: hostel-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: hostel-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hostel-secrets
              key: DB_PASSWORD
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: hostel-secrets
              key: OPENAI_API_KEY
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: hostel-service
spec:
  selector:
    app: hostel-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer